language: rust
rust:
  - stable
cache: cargo

jobs:
  include:
    - stage: deploy
      script: ./prepare-pages.sh
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd output && ../rust_out)
        skip_cleanup: true
        on:
          branch: master
